var content_jp = {
    name: "Yeajin Park",
    name_sub: "",
    headline_1: "初めまして。朴(パク)イェジンと申します。",
    headline_2: "アモーレパシフィックジャパン株式会社でETUDE HOUSE公式サイトの運営に携わっております。",
	headline_3: "主にWeb広告の運用管理・SEO対策・ディレクションを担当しております。",
    headline_4: "前職ではWebプランナー、Webデザイナーとして、自社モールの運営及びECサイトを中心に制作業務を担当しておりました。",
    exp1_body_title: "アモーレパシフィックジャパン株式会社(化粧品の製造及び販売)",
    exp1_body_title_sub: "化粧品メーカーのアジアランキング3位。韓国での全国シェア率は40％と日本における資生堂的な存在",
    exp1_sub_title_1: "ETUDE HOUSE公式サイトの運営",
    exp1_sub_title_2: "エチュードハウス(https://www.etudehouse.com)",
    exp1_sub_title_3: "500万PV/月　※運営メンバー6名",
    exp1_sub_title_4: "□ブランド紹介：10代後半から20代をターゲットにリップ、アイシャドウなどカラーメイクを中心に商品を展開",
    exp1_sub_title_5: "□毎月新商品をリリース(平均3～5商品 SKU数30)",
    exp1_sub_title_6: "□実店舗とオンラインの売上割合：9：1(オンライン1割)",
    exp1_sub_title_7: "担当業務 : 広告運用管理 、SEO対策、制作のディレクション、メルマガ/LINE＠配信、本社(韓国)との連携業務",
    exp1_list_1: "広告運用管理 (予算 600万円/月)",
    exp1_list_1_1: "運用媒体（Google Adwords/Yahoo!プロモーション/Criteo/Facebook/LINE/Amazon advertising）",
    exp1_list_1_2: "自社商品への興味・関心が高まる時期に配信を強化し、顕在層にアプローチすることで費用対効果を最大化。",
    exp1_list_1_3: "さらに、来訪ユーザーデータを細分化し、リターゲティング広告で活用することで効率を改善。",
    exp1_list_1_4: "広告経由の売上を約60％アップ。",
    exp1_list_1_5: "2018年6月：500万円(月)→2019年6月：800万円(月)",
    exp1_list_2: "会員獲得施策",
    exp1_list_2_1: "非会員をターゲットに会員登録を必須とするお得なキャンペーンのリターゲティング広告を実施。",
    exp1_list_2_2: "広告からの新規会員獲得数を約30％アップ。",
    exp1_list_2_3: "2018年 平均1,500(月) →2019年 平均2,000(月)",
    exp1_list_3: "SEO施策",
    exp1_list_3_1: "検索エンジンのアップデートに合わせて迅速に対応（重複ページ/canonicalタグ/構造化マークアップ/記事制作など）し、サイトの評価を高め集客に貢献。",
    exp1_list_3_2: "自然流入セッションを約10万アップ。",
    exp1_list_3_3: "2018年5月：18万(月)→2019年5月：28万(月)",
    exp1_list_4: "制作のディレクション",
    exp1_list_4_1: "毎月の新商品(平均3～5商品)発売に合わせ、イベント及びプロモーションページのディレクションを担当。",
    exp1_list_4_2: "スピード感のある対応とブランドのグローバル戦略に基づき、モデル画像の使用、コラボレーション商品の公式サイトでの伝え方について関連部署と連携をしながら業務を遂行。",
    exp2_body_title: "株式会社Eストアー(ネット通販総合支援)",
    exp2_sub_title_1: "モール型ECサイトの運営(2013年4月～2014年8月)",
    exp2_sub_title_2: "パーク（http://park.jp/※現在サービス終了）",
    exp2_sub_title_3: "700万PV/月　600万商品掲載　※運営メンバー40名",
    exp2_sub_title_4: "担当業務 : アクセス解析、SEO対策、キーワード広告運営、Web広告予算管理、プロモーション企画",
    exp2_list_1: "サイト分析",
    exp2_list_1_1: "訪問者の購入経路、サイト内行動パタン、転換率の分析データをもとに事業方針を決定することに貢献。",
    exp2_list_1_2: "また、購入データの分析を通し、サイトの売れ筋カテゴリーに注力するマーケティングを行う。",
    exp2_list_1_3: "サイト全体の商流額1億2千万円アップ。",
    exp2_list_1_4: "2013年4月：2億8千万円(月) →2014年6月：4億円(月)",
    exp2_list_2: "Yahoo, Google キーワード広告運営 (予算 600万円/月)",
    exp2_list_2_1: "世の中のトレンドとサイトの注力カテゴリーを分析し、予算配分及びキーワード調整を担当。",
    exp2_list_2_2: "ROAS 400%を向上させ、広告収益率を2倍近く増大させる。",
    exp2_list_2_3: "2014年5月 ROAS 400%(月) →2014年8月 ROAS 800%(月)",
    exp2_list_3: "提携先モール型ECサイトへの商品露出及び調整(予算 800万円/月)",
    exp2_list_3_1: "媒体事に強いカテゴリーを選定しCPA、CPC方式で運営。",
    exp2_list_3_2: "月1億2千万円の売上を安定して創出することで、事業拡大に貢献",
    exp2_sub_title_5: "制作(2014年9月～2018年3月)",
    exp2_sub_title_6: "担当業務 : ディレクション、デザイン、コーディング（HTML,CSS）",
    exp2_sub_title_7: "クライアントへのヒアリングからコンセプト決め、写真撮影、サイトマップ作成、デザイン提案、コーディング、納品まで、一連の流れを担当しました。",
    exp2_list_4: "ECサイトを中心に立ち上げ制作、リニューアル制作、商品ページ制作、LP制作、メルマガ制作を担当。",
    exp2_list_4_1: "機械の部品から食品、化粧品など、多岐にわたる業界のサイトを100件以上制作",
    exp2_list_4_2: "フォートフォリオ: yeajinpark.github.io",
    exp2_list_4_3: "2016年4月~2017年3月 デザイン学校就学（グラフィックデザイン/アートディレクターコース）",
    edu1_body_title: "デザイン学校就学（バンタンデザイン研究所）",
    edu1_list_1: "グラフィックデザインコース",
    edu1_list_2: "アートディレクターコース",
    edu2_body_title: "大阪産業大学　経営学部　流通学科",
    edu3_body_title: "日本語能力試験1級取得",
    edu4_body_title: "柳川高等学校　国際科",
    site_name_title: "サイト名：",
    product_class_title: "取扱商品：",
    producing_period_title: "制作期間：",
    product_scale_title: "案件規模：",
    project_content_title: "業務内容：",
    project_point_title: "制作のポイント：",
    project_achievements_title: "成果：",
    project_brand_title: "ブランド：",
    project_brand_new_title: "【新規立ち上げ】",
    project_renewal_title: "【リニューアル制作】",
    project_teaser_lp_title: "【ティザーサイト・LP制作】",
    project_lp_title: "【LP制作】",
    timeline1_1: "全国選抜高校テニス大会　団体戦3位",
    timeline1_2: "柳川高等学校（テニス留学）",
    timeline1_3: "_福岡",
    timeline2_1: "韓国国体（海外同胞部）2回出場",
    timeline2_2: "団体戦・個人戦1位",
    timeline2_3: "大阪産業大学経営学部流通学科",
    timeline2_4: "_大阪",
    timeline3_1: "ベストチーム賞　2年連続受賞",
    timeline3_2: "株式会社Eストアー",
    timeline3_3: "クリエイティブチーム在籍",
    timeline3_4: "_東京",
    timeline4_1: "アモーレパシフィックジャパン株式会社（化粧品の製造及び販売）",
    timeline4_2: "•ETUDE HOUSE公式サイトの運営",
    timeline4_3: "",
    timeline4_4: "_東京",
    modal1_title: "いずみBODYラボ",
    modal1_scale: "240万円",
    modal1_list_1: "TOPページ/LP/各階層ページ",
    modal1_list_2: "ロゴ制作（サイトロゴ/ Princessシリーズブランドロゴ)",
    modal1_list_3: "サイト構成/撮影イメージ/キャッチコピーの作成",
    modal1_content_1: "コンプレックスに寄り添う機能性商品をはじめ、有名イラスト作家とのコラボ商品まで様々なブランド展開を行っているため、白を基調としたシンプルなデザインにし各ブランドの世界観が引き立つようにしました。",
    modal1_content_2: "また、コーポレートカラーであるピンクをアクセントカラーとして取り入れ、企業イメージに一貫性を持たせました。",
    modal1_content_3: "「ぽっちゃり女子向けファッション誌 lafarfaとのコラボ企画」",
    modal1_content_4: "大きめのサイズでもデザインも機能性も諦めたくない！<ありのままの自分を好きになる下着>をコンセプトに開発された新ブランドGlamour Princess。",
    modal1_content_5: "メインとなるターゲット層が10代後半から20代前半であることから、スマホでの使い勝手や見栄えを考慮しデザインしました。",
    modal1_content_6: "また、商品のコンセプトであるおしゃれで可愛いを表現するために手書き風素材をメインで使用し、イラストとページ全体の動きを工夫しました。",
    modal2_title: "協和医療器",
    modal2_scale: "10万円",
    modal2_content_1: "商品を使用した時のフレッシュな感覚とくつろぎ、息抜きなどのリラクゼーション効果をイメージできるよう、気泡や自然のイメージ画像を取り入れ全体をやさしい色合いでまとめました。また、レスポンシブ対応であることから各デバイスごとのUIを考慮し、テキストの大きさや量、画像サイズを調整しました。",
    modal3_title: "COSMETICS TACT-JAPAN",
    modal3_scale: "20万円",
    modal3_content_1: "商品を使用した時の爽快感を伝えるため、色の組み合わせを工夫し、実物の写真を多く取り入れました。また、商品の効果を知ってもらうためにお客様のレビューと認定情報を多く入れることで、購入者に納得してもらえるような構成を意識しました。",
    modal4_title: "日本一こだわり卵 SAILOR",
    modal4_scale: "25万円",
    modal4_content_1: "品質の良さを伝えたいという要望をいただき、生産過程でのこだわりポイントを具体的に表現しまいた。また、商品の鮮度が伝わるよう画像のトリミングを行い、シズル感を出しました。",
    modal5_title: "築地のお魚岩瀬",
    modal5_scale: "30万円",
    modal5_content_1: "サイトの転換率を前年同期比3%向上",
    modal5_content_2: "2015年8～11月転換率5%(月) -> 2016年8～11月転換率8% (月)",
    modal5_content_3: "★リニューアルの理由：商品が探しづらい構成、海産物の新鮮度が伝わりにくい",
    modal5_content_4: "商品の新鮮度を伝えるため、画像の面積を大きくし、シズル感を伝えるための工夫をしました。また、売れ筋商品のカテゴリーをバナーで制作することで、スムーズにユーザーを誘導できるようにしました。",
    modal6_title: "丹後王国匠庵別館",
    modal6_scale: "50万円",
    modal6_content_1: "シンプルで高級感のあるイメージ、かつ親しみやすい雰囲気の要望をいただき、テキストの量を極力減らし落ち着いたカラーを使用しました。",
    modal6_content_2: "また、食品を扱うサイトなので、信頼度を上げるために生産者やスタッフなど、人物の顔写真を多く取り入れました。",
    modal1_product_class: "女性下着",
    modal2_product_class: "健康/美容医療器",
    modal3_product_class: "シャンプー",
    modal4_product_class: "食品・加工食品・調味料",
    modal5_product_class: "海産物",
    modal6_product_class: "生産者直接仕入れの食品や自社生産の食品",
    modal1_project_content: "デザイン担当",
    modal2_project_content: "デザイン担当（ティザーサイト/LP）※レスポンシブデザイン",
    modal3_project_content: "デザインからコーディングまですべてを担当",
    modal4_project_content: "デザインからコーディングまですべてを担当",
    modal5_project_content: "デザインからコーディングまですべてを担当",
    modal6_project_content: "デザインからコーディングまですべてを担当"

};
var content_kr = {
    name: "Yeajin Park",
    name_sub: "",
    headline_1: "안녕하세요. 박 예진 입니다.",
    headline_2: "아모레 퍼시픽 재팬 주식회사에서 ETUDE HOUSE 공식 사이트의 운영을 담당하고 있습니다.",
	headline_3: "주 업무는 Web 광고 운영 관리, SEO, 디렉션 입니다.",
    headline_4: "이전 회사에서는 Web 플래너, Web 디자이너로 자사 쇼핑몰 운영 및 EC 사이트를 중심으로 제작 업무를 담당했습니다.",
    exp1_body_title: "아모레 퍼시픽 재팬 주식회사 (화장품 제조 및 판매)",
    exp1_body_title_sub: "화장품 메이커의 아시아 랭킹 3 위. 한국에서의 전국 점유율은 40 %.",
    exp1_sub_title_1: "ETUDE HOUSE 공식 사이트 운영",
    exp1_sub_title_2: "ETUDE HOUSE (www.etudehouse.com)",
    exp1_sub_title_3: "500 만 PV / 월 ※ 운영 멤버 6 명",
    exp1_sub_title_4: "□ 브랜드 소개 : 10 대 후반에서 20 대를 타겟으로 입술, 아이섀도 등 컬러 메이크업을 중심으로 상품을 전개",
    exp1_sub_title_5: "□ 매월 신상품 출시 (평균 3 ~ 5 제품 SKU 30)",
    exp1_sub_title_6: "□ 실제 매장과 온라인 매출 비율 : 9 : 1 (온라인 10 %)",
    exp1_sub_title_7: "담당 업무 : 광고 운영 관리, SEO 대응, 제작 디렉션, 매거진 / LINE @ 메시지, 본사 (한국)과의 연계 업무",
    exp1_list_1: "광고 운영 관리 (예산 600 만엔 / 월)",
    exp1_list_1_1: "운용 매체 (Google Adwords / Yahoo! 프로모션 / Criteo / Facebook / LINE / Amazon advertising)",
    exp1_list_1_2: "자사 상품에 대한 관심이 높아지는 주에 광고를 강화하고 관심층에 접근하여 비용 대비 효과를 극대화.",
    exp1_list_1_3: "내방 사용자 데이터를 세분화 한 리 타게팅 광고 효율성을 개선.",
    exp1_list_1_4: "광고를 통해 매출을 약 40 % 향상.",
    exp1_list_1_5: "2018 년 6 월 : 500 만엔 (월) → 2019 년 6 월 : 800 만엔 (월)",
    exp1_list_2: "회원 가입 마케팅",
    exp1_list_2_1: "비회원을 대상으로 회원 등록을 요구하는 캠페인의 리 타게팅 광고를 실시.",
    exp1_list_2_2: "광고를 통해 신규 회원 가입수를 약 30 % 향상. ",
    exp1_list_2_3: "2018 년 평균 1,500 (월) → 2019 년 평균 2,000 (월)",
    exp1_list_3: "SEO 대응",
    exp1_list_3_1: "검색 엔진의 업데이트에 따라 신속하게 대응 (중복 페이지 / canonical tag / 구조화 markup / 기사 제작 등)하여 사이트의 평가를 높여 고객 유치에 기여.",
    exp1_list_3_2: "자연 유입 사용자를 약 50 % 향상.",
    exp1_list_3_3: "2018 년 5 월 : 18 만 (월) → 2019 년 5 월 : 28 만 (월)",
    exp1_list_4: "제작 방향 디렉션",
    exp1_list_4_1: "매월 신상품 (평균 3 ~ 5 제품) 출시에 맞춰 이벤트 및 프로모션 페이지의 디렉션을 담당.",
    exp1_list_4_2: "속도감 있게 브랜드의 글로벌 전략에 따라 모델 이미지의 사용, 공동 상품 Web상에서의 표현에 대해 관련 부서와 협력을하면서 업무를 수행.",
    exp2_body_title: "주식회사 E 스토어",
    exp2_sub_title_1: "몰형 EC 사이트 운영 (2013 년 4 월 ~ 2014 년 8 월)",
    exp2_sub_title_2: "Park（http://park.jp/※ 현재 서비스 종료)",
    exp2_sub_title_3: "700 만 PV / 월 600 만 상품 게재 ※ 운영 멤버 40 명",
    exp2_sub_title_4: "담당 업무 : 액세스 분석, SEO 대응 키워드 광고 운영, Web 광고 예산 관리, 프로모션 기획",
    exp2_list_1: "사이트 분석",
    exp2_list_1_1 : "방문자의 구매 경로, 사이트 내 행동 패턴 전환율 분석 데이터를 바탕으로 사업 방침을 결정하는 데 기여.",
    exp2_list_1_2 : "또한 구매 데이터의 분석을 통해 사이트의 히트 카테고리에 주력하는 마케팅을 실시.",
    exp2_list_1_3 : "사이트 전체의 상류 금액 1 억 2 천만 엔까지.",
    exp2_list_1_4 : "2013 년 4 월 : 2 억 8 천만 엔 (월) → 2014 년 6 월 : 4 억엔 (월)",
    exp2_list_2 : "Yahoo, Google 키워드 광고 운영 (예산 600 만엔 / 월)",
    exp2_list_2_1 : "트렌드와 사이트의 주력 카테고리를 분석하고 예산 배분 및 키워드 조정을 담당.",
    exp2_list_2_2 : "ROAS 400 %를 향상시켜 광고 수익을 2 배 가까이 증가.",
    exp2_list_2_3 : "2014 년 5 월 ROAS 400 % (월) → 2014 년 8 월 ROAS 800 % (월)",
    exp2_list_3 : "파트너사의 몰형 EC 사이트에 상품 노출 및 조정 (예산 800 만엔 / 월)",
    exp2_list_3_1 : "미디어에 적합한 카테고리를 선정 CPA, CPC 방식으로 운영",
    exp2_list_3_2 : "월 1 억 2 천만 엔의 매출을 안정적으로 창출하여 사업 확대에 기여",
    exp2_sub_title_5 : "제작 (2014 년 9 월 ~ 2018 년 3 월)",
    exp2_sub_title_6 : "담당 업무 : 디렉션, 디자인, 코딩 (HTML, CSS)",
    exp2_sub_title_7 : "고객의 요구에 따라 컨셉 결정, 사진, 사이트 맵 생성, 디자인 제안, 코딩 납품까지 일련의 흐름을 담당.",
    exp2_list_4 : "EC 사이트를 중심으로 신규 제작, 리뉴얼 제작, 상품 페이지 제작, LP 제작 매거진 제작을 담당.",
    exp2_list_4_1 : "기계 부품에서 부터 식품, 화장품 등 다양한 산업의 사이트를 100 개 이상 제작",
    exp2_list_4_2 : "포트폴리오 : yeajinpark.github.io",
    exp2_list_4_3 : "디자인 학교를 주말 코스에서 1 년간 통학 (그래픽 디자인 / 아트 디렉터 코스)",
    edu1_body_title: "디자인 학교 취학 (Vantan 디자인 연구소)",
    edu1_list_1: "그래픽 디자인 과정",
    edu1_list_2: "아트 디렉터 코스",
    edu2_body_title: "오사카 산업 대학 경영 학부 유통학과",
    edu3_body_title: "일본어 능력 시험 1 급 취득",
    edu4_body_title: "야나가와 고등학교 국제학과",
    site_name_title: "사이트 명:",
    product_class_title: "취급 상품:",
    producing_period_title: "제작 기간:",
    product_scale_title: "프로젝트 규모:",
    project_content_title: "업무 내용:",
    project_point_title: "사이트 제작 포인트:",
    project_achievements_title: "성과:",
    project_brand_title: "브랜드:",
    project_brand_new_title: "【신규 제작】",
    project_renewal_title: "【리뉴얼 프로젝트】",
    project_teaser_lp_title: "【티저 사이트, Landing Page 작성】",
    project_lp_title: "【Landing Page 작성】",
    timeline1_1: "전국 선발 고등학교 테니스 대회 단체전 3 위",
    timeline1_2: "야나가와 고등학교 (테니스 유학)",
    timeline1_3: "_규슈 후쿠오카",
    timeline2_1: "한국 국체 (해외 동포 부) 2 회 출전",
    timeline2_2: "단체전 · 개인전 1 위",
    timeline2_3: "오사카 산업 대학 경영 학부 유통학과",
    timeline2_4: "_칸사이 오사카",
    timeline3_1: "베스트 팀 상 2 년 연속 수상",
    timeline3_2: "주식회사 E Store",
    timeline3_3: "크리에이티브 팀 소속",
    timeline3_4: "_칸토 도쿄",
    timeline4_1: "아모레 퍼시픽 재팬 주식회사",
    timeline4_2: "• ETUDE HOUSE 공식 사이트 운영",
    timeline4_3: "",
    timeline4_4: "_칸토 도쿄",
	modal1_title: "이주미 BODY 라보",
    modal1_scale: "240 만엔",
    modal1_list_1: "TOP page / Landing Page / 각 계층 페이지",
    modal1_list_2: "로고 제작 (사이트 로고 / Princess 시리즈 브랜드 로고)",
    modal1_list_3: "사이트 구성 / 촬영 이미지 / 카피 문구 작성",
    modal1_content_1: "컴플렉스에 동행 기능성 제품을 비롯해 유명 일러스트 작가와의 콜라보레이션 상품까지 다양한 브랜드 전개를 실시하고 있기 때문에 흰색을 기조로 한 심플한 디자인으로 각 브랜드의 세계관이 돋보이게했습니다.",
    modal1_content_2: "또한, 기업 컬러 인 핑크를 악센트 컬러로 도입 기업 이미지에 일관성을 갖게되었습니다.",
    modal1_content_3: "\"통통한 여자를위한 패션 잡지 lafarfa과의 합작 기획\"",
    modal1_content_4: "큰 사이즈도 디자인도 기능도 포기하고 싶지 않아!  <있는 그대로의 자신을 사랑 할거야 속옷>을 컨셉으로 개발 된 새로운 브랜드 Glamour Princess!",
    modal1_content_5: "메인이되는 타겟층이 10 대 후반에서 20 대 초반이기 때문에, 스마트 폰의 사용성이나 모양을 고려하여 디자인했습니다.",
    modal1_content_6: "또한 제품의 컨셉 인 세련되고 귀여운를 표현하기 위해 필기 바람 소재를 메인으로 사용하고 그림과 페이지 전체의 움직임을 연구했습니다.",
    modal2_title: "쿄와의료기",
    modal2_scale: "10 만엔",
    modal2_content_1: "제품을 사용했을 때의 신선한 감각과 휴식, 휴식 등의 휴식 효과를 이미지 할 수 있도록 거품과 자연의 이미지를 도입 전체를 부드러운 색조로 정리했습니다. 또한 Responsive 대응이기 때문에 각 장치마다의 UI를 고려하여 텍스트의 크기, 양, 이미지 크기를 조정했습니다.",
    modal3_title: "COSMETICS TACT-JAPAN",
    modal3_scale: "20 만엔",
    modal3_content_1: "상품을 사용했을때 느끼는 시원하고 개운한 느낌을 표현하기 위해 색상 대비를 통해 돋보이게 하였습니다.",
    modal4_title: "일본 제일 엄선한 달걀 SAILOR",
    modal4_scale: "25 만엔",
    modal4_content_1: "신선함과 상품에 품질을 전달하고 싶다는 고객 요구에 따라 상품의 생산과정을 자세하게 콘텐츠에 담아 고객이 안심하고 구매할수 있도록 하였습니다.",
    modal5_title: "키쿠치 생선 이와세",
    modal5_scale: "30 만엔",
    modal5_content_1: "사이트의 전환율을 전년 동기 대비 3 % 증가 ",
    modal5_content_2: "2015 년 8 ~ 11 월 전환율 5 % (월) -> 2016 년 8 ~ 11 월 전환율 8 % (월)",
    modal5_content_3: "・리뉴얼 이유：해산물에 신선도가 전해지지 않는것과 주력 상품으로의 유도문제",
    modal5_content_4: "상품에 면적을 크게하여 신선도를 전달하였고 주력 카테고리 별로 상품배너를 제작하여 고객을 유도하였습니다. 또한 밝은 느낌에 귀엽고 친근한 이미지의 고객 요구에 따라 전체적으로 모서리가 둥근 일러스트를 사용하였습니다.",
    modal6_title: "쿄토탄고의 쌀과 선물을 판매하는사이트",
    modal6_scale: "50 만엔",
    modal6_content_1: "고급스러우면서도 심플하고 친근한 느낌의 고객 요구에 따라 상품 설명은 짧은 문장으로 간결하게 정리하였고 차분한 색상 사용으로 고급스러움을 표현하였습니다.",
    modal6_content_2: "또한 식품 사이트인 만큼 신뢰감이 중요하기 때문에 생산자와 스텝에 얼굴 사진을 배너에 넣어 제작하였습니다.",
    modal1_product_class: "여성 속옷",
    modal2_product_class: "건강/미용의료기기",
    modal3_product_class: "소금 샴푸",
    modal4_product_class: "달걀,농축수산물",
    modal5_product_class: "해산물",
    modal6_product_class: "쌀,맥주,농축수산물,지역상품",
    modal1_project_content: "디자인 담당",
    modal2_project_content: "디자인 담당 (Landing Page) * Responsive 디자인",
    modal3_project_content: "디자인 및 코딩 전체를 담당",
    modal4_project_content: "디자인 및 코딩 전체를 담당 (고정 템플릿)",
    modal5_project_content: "디자인 및 코딩 전체를 담당 (고정 템플릿)",
    modal6_project_content: "디자인 및 코딩 전체를 담당 (고정 템플릿)"
};