var content_jp = {
    name: "Yeajin Park (パク イェジン)",
    headline_1: "初めまして。Webデザイナー３年目の朴イェジンと申します。",
    headline_2: "ECサイトを中心に新規立ち上げ制作・リニューアル制作・LP制作のデザイン、 コーディング（HTML/CSS）を担当しました",
    site_name_title: "サイト名：",
    product_class_title: "取扱商品：",
    producing_period_title: "制作期間：",
    product_scale_title: "案件規模：",
    project_content_title: "業務内容：",
    project_point_title: "制作のポイント：",
    project_achievements_title: "成果：",
    project_brand_title: "ブランド：",
    project_brand_new_title: "【新規立ち上げ】",
    project_renewal_title: "【リニューアル制作】",
    project_teaser_lp_title: "【ティザーサイト・LP制作】",
    project_lp_title: "【LP制作】",
    timeline1_1: "柳川高等学校テニス留学",
    timeline1_2: "テニス（全国高校選抜団体戦4位）",
    timeline1_3: "_福岡",
    timeline2_1: "大阪産業大学経営学部流通学科",
    timeline2_2: "韓国国体（海外同胞部）出場1位",
    timeline2_3: "_大阪",
    timeline3_1: "株式会社Eストアー（ネット通販総合支援事業）",
    timeline3_2: "☆モール型ECサイトの運営及びWeb広告を担当",
    timeline3_3: "☆ECサイトの制作",
    timeline3_4: "_東京"
};
var content_kr = {
    name: "Yeajin Park (박 예진)",
    headline_1: "처음 뵙겠습니다. Web 디자이너 3 년차 박 예진라고합니다.",
    headline_2: "EC 사이트를 중심으로 새 출범 제작 리뉴얼 제작 · LP 제품 디자인, 코딩 (HTML / CSS)을 담당했습니다",
    site_name_title: "사이트 명:",
    product_class_title: "취급 상품:",
    producing_period_title: "제작 기간:",
    product_scale_title: "프로젝트 규모:",
    project_content_title: "업무 내용:",
    project_point_title: "제작 포인트:",
    project_achievements_title: "성과:",
    project_brand_title: "브랜드:",
    project_brand_new_title: "【신규 프로젝트】",
    project_renewal_title: "【리뉴얼 프로젝트】",
    project_teaser_lp_title: "【티저 사이트, Landing Page 작성】",
    project_lp_title: "【Landing Page 작성】",
    timeline1_1: "야나가와 고등학교 테니스 유학",
    timeline1_2: "테니스 (전국 고교 선발 단체전 4 위)",
    timeline1_3: "_후쿠오카",
    timeline2_1: "오사카 산업 대학 경영 학부 유통학과",
    timeline2_2: "대한민국 전국체전 (해외 동포 부) 출전 1 위",
    timeline2_3: "_오사카",
    timeline3_1: "주식회사 E 스토어 (인터넷 쇼핑몰 종합 지원 사업)",
    timeline3_2: "* E-Commerce 사이트의 운영 및 Web 광고 담당",
    timeline3_3: "* E-Commerce 사이트 제작",
    timeline3_4: "_도쿄"
};