var content_jp = {
    name: "Yeajin Park (パク イェジン)",
    headline_1: "初めまして。朴イェジンと申します。",
    headline_2: "大阪産業大学経営学部流通学科卒業後、2013年4月株式会社Eストアーへ入社し、5年間Webプランナー・Webデザイナーとして、自社モールの運営及びECサイトを中心に制作業務を担当しておりました。",
	headline_3: "2018年4月よりアモーレパシフィックジャパン株式会社へ転職し、ETUDE HOUSE公式サイトのEC運営担当としてWeb広告の運用管理・SEO・プロモーションページのディレクションを担当しております。",
    site_name_title: "サイト名：",
    product_class_title: "取扱商品：",
    producing_period_title: "制作期間：",
    product_scale_title: "案件規模：",
    project_content_title: "業務内容：",
    project_point_title: "制作のポイント：",
    project_achievements_title: "成果：",
    project_brand_title: "ブランド：",
    project_brand_new_title: "【新規立ち上げ】",
    project_renewal_title: "【リニューアル制作】",
    project_teaser_lp_title: "【ティザーサイト・LP制作】",
    project_lp_title: "【LP制作】",
    timeline1_1: "柳川高等学校テニス留学",
    timeline1_2: "テニス（全国高校選抜団体戦3位）",
    timeline1_3: "_福岡",
    timeline2_1: "大阪産業大学経営学部流通学科",
    timeline2_2: "韓国国体（海外同胞部）出場1位",
    timeline2_3: "_大阪",
    timeline3_1: "株式会社Eストアー（ネット通販総合支援事業）",
    timeline3_2: "☆モール型ECサイトの運営及びWeb広告を担当",
    timeline3_3: "☆ECサイトの制作",
    timeline3_4: "_東京",
    timeline4_1: "アモーレパシフィックジャパン株式会社",
    timeline4_2: "☆モール型ECサイトの運営及びWeb広告を担当",
    timeline4_3: "☆ECサイトの制作",
    timeline4_4: "_東京",
    modal1_title: "いずみBODYラボ",
    modal2_title: "協和医療器",
    modal3_title: "COSMETICS TACT-JAPAN",
    modal4_title: "日本一こだわり卵 SAILOR",
    modal5_title: "築地のお魚岩瀬",
    modal6_title: "丹後王国匠庵別館",
    modal1_product_class: "女性下着",
    modal2_product_class: "健康/美容医療器",
    modal3_product_class: "シャンプー",
    modal4_product_class: "食品・加工食品・調味料",
    modal5_product_class: "海産物",
    modal6_product_class: "生産者直接仕入れの食品や自社生産の食品",
    modal1_project_content: "デザイン担当",
    modal2_project_content: "デザイン担当（ティザーサイト/LP）※レスポンシブデザイン",
    modal3_project_content: "デザインからコーディングまですべてを担当",
    modal4_project_content: "デザインからコーディングまですべてを担当",
    modal5_project_content: "デザインからコーディングまですべてを担当",
    modal6_project_content: "デザインからコーディングまですべてを担当"

};
var content_kr = {
    name: "Yeajin Park (박 예진)",
    headline_1: "안녕하세요. 박 예진 입니다.",
    headline_2: "오사카 산업 대학 경영 학부 유통학과 졸업 후, 2013 년 4 월 주식회사 E 스토어에 입사 해 5 년간 Web 플래너 Web 디자이너로 자사 쇼핑몰 운영 및 EC 사이트를 중심으로 제작 업무를 담당했습니다.",
	headline_3: "2018 년 4 월부터 아모레 퍼시픽 재팬 주식회사에서 ETUDE HOUSE 공식 사이트 EC 운영 담당으로 Web 광고 운영 관리 · SEO 프로모션 페이지의 디렉션을 담당하고 있습니다.",
    site_name_title: "사이트 명:",
    product_class_title: "취급 상품:",
    producing_period_title: "제작 기간:",
    product_scale_title: "프로젝트 규모:",
    project_content_title: "업무 내용:",
    project_point_title: "사이트 제작 포인트:",
    project_achievements_title: "성과:",
    project_brand_title: "브랜드:",
    project_brand_new_title: "【신규 제작】",
    project_renewal_title: "【리뉴얼 프로젝트】",
    project_teaser_lp_title: "【티저 사이트, Landing Page 작성】",
    project_lp_title: "【Landing Page 작성】",
    timeline1_1: "야나가와 고등학교 테니스 유학",
    timeline1_2: "전국 선발 고교 테니스대회 단체전3위 입상",
    timeline1_3: "_규슈 후쿠오카",
    timeline2_1: "오사카 산업 대학 경영 학부 유통학과",
    timeline2_2: "대한민국 전국체전 (해외 동포 부) 출전 1위",
    timeline2_3: "_칸사이 오사카",
    timeline3_1: "주식회사 E 스토어 (전자상거래 서버 렌탈 및 운영대행 기업)",
    timeline3_2: "* E-Commerce 사이트의 운영 및 온라인 광고 담당",
    timeline3_3: "* E-Commerce 사이트 디자인 및 제작",
    timeline3_4: "_칸토 도쿄",
    timeline4_1: "아모레 퍼시픽 재팬 주식회사",
    timeline4_2: "☆モール型ECサイトの運営及びWeb広告を担当",
    timeline4_3: "☆ECサイトの制作",
    timeline4_4: "_칸토 도쿄",
	modal1_title: "이주미 BODY 라보",
    modal2_title: "쿄와의료기",
    modal3_title: "COSMETICS TACT-JAPAN",
    modal4_title: "일본 제일 엄선한 달걀 SAILOR",
    modal5_title: "키쿠치 생선 이와세",
    modal6_title: "쿄토탄고의 쌀과 선물을 판매하는사이트",
    modal1_product_class: "여성 속옷",
    modal2_product_class: "건강/미용의료기기",
    modal3_product_class: "소금 샴푸",
    modal4_product_class: "달걀,농축수산물",
    modal5_product_class: "해산물",
    modal6_product_class: "쌀,맥주,농축수산물,지역상품",
    modal1_project_content: "디자인 담당",
    modal2_project_content: "디자인 담당 (Landing Page) * Responsive 디자인",
    modal3_project_content: "디자인 및 코딩 전체를 담당",
    modal4_project_content: "디자인 및 코딩 전체를 담당 (고정 템플릿)",
    modal5_project_content: "디자인 및 코딩 전체를 담당 (고정 템플릿)",
    modal6_project_content: "디자인 및 코딩 전체를 담당 (고정 템플릿)"
};